Build and deploy from github on openshift
IBM-Bluemix/get-started-node pull request #55
Opened 2021-08-06 08:28 UTC by henrynash

On Openshift, we should use the ability to build and deploy directly from GitHub source, rather than have people build their own image using docker. This also prevents issues of ensuring you have access to the IBM Cloud container registry.

It is a pity that `oc new-app...` does not provide an ability to pass in a secret to be exposed via environment variables in the application instance (it does support it for the build instance). Hence the requirement to patch the deployment after the build. I'm open to a better way of doing this (that does not require cloning and modifying the source).

2021-08-13 07:14 UTC, hickeyma requested changes
I like this as it uses the build capabilities in OpenShift to deploy easily. Thanks for pushing these changes @henrynash. Just few small things to address.

2021-08-13 07:14 UTC, hickeyma commented on README-OpenShift.md
> +2. Access your application via the URL given in the HOST/PORT column, which will be of the form `get-started-node-.....containers.appdomain.cloud`
Can you explicitly specify that it is HTTP and NOT HTTPS for the URL?

2021-08-13 07:14 UTC, hickeyma commented on README-OpenShift.md
> +You should also delete any build pods that were generated by building from source.
Would it be worth adding a link/instructions on how to do this?

2021-08-13 13:45 UTC, henrynash commented on README-OpenShift.md
> +2. Access your application via the URL given in the HOST/PORT column, which will be of the form `get-started-node-.....containers.appdomain.cloud`
Added comment to clarify this is HTTP.

2021-08-13 13:45 UTC, henrynash commented on README-OpenShift.md
> +You should also delete any build pods that were generated by building from source.
Add command to do this.

2021-08-13 13:45 UTC, henrynash commented
Thanks your review @hickeyma, fixed up accordingly.

2021-08-13 13:54 UTC, hickeyma approved these changes
LGTM, thanks @henrynash

2021-08-13 13:56 UTC, hickeyma commented
@kevin-ortega Do you mind reviewing this PR when you get a chance?

2021-08-13 17:51 UTC, kevin-ortega approved these changes

2021-08-13 17:51 UTC, merged

2021-08-16 07:36 UTC, hickeyma commented
Thanks @kevin-ortega